import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import Header from '../components/Header';
import Footer from '../components/Footer';
import ReactMarkdown from 'react-markdown';
import { themeData } from '../data/themeData';

const TermsPage: React.FC = () => {
  const navigate = useNavigate();

  // Static content directly in the file
  const document = {
    title: 'Terms of Use',
    last_updated: 'December 2025',
    content: `Welcome to DatingAdvice.io. By accessing or using our website, you agree to be bound by these Terms of Use.

**1. Acceptance of Terms**

By using our services, you confirm that you are at least 18 years old and capable of entering into a binding contract.

**2. Nature of Service (AI Disclaimer)**

DatingAdvice.io provides guidance generated by Artificial Intelligence. This advice is for entertainment and informational purposes only. It does not constitute professional psychological, medical, or legal advice. You should not rely solely on this information for making significant life decisions.

**3. User Conduct**

You agree not to:
- Use the service for any illegal purpose.
- Harass, threaten, or intimidate others.
- Attempt to reverse engineer our AI models.

**4. Intellectual Property**

All content, branding, and software on DatingAdvice.io are the property of DatingAdvice.io and are protected by copyright laws.

**5. Termination**

We reserve the right to suspend or terminate your account at our discretion if you violate these terms.`
  };

  return (
    <div className="min-h-screen flex flex-col" style={{ backgroundColor: themeData.colors.bgSoft }}>
      <Helmet>
        <title>{document.title} | DatingAdvice.io</title>
        <meta name="description" content="Read our Terms of Use to understand the rules and regulations for using the DatingAdvice.io platform." />
      </Helmet>
      <Header />
      <main className="flex-grow pt-32 pb-20 px-6">
        <div className="max-w-[800px] mx-auto">
          <button
            onClick={() => {
              navigate('/');
              window.scrollTo(0, 0);
            }}
            className="text-sm font-bold opacity-50 hover:opacity-100 mb-8 inline-block transition-opacity cursor-pointer"
          >
            ← BACK TO HOME
          </button>

          <h1 className="text-4xl md:text-5xl font-bold mb-4" style={{ fontFamily: 'DM Serif Display' }}>{document.title}</h1>
          <p className="text-sm opacity-50 mb-10 uppercase tracking-widest font-semibold">Last Updated: {document.last_updated}</p>
          <div className="prose prose-pink text-lg leading-relaxed space-y-6 opacity-80" style={{ color: themeData.colors.textBody }}>
            <ReactMarkdown>{document.content}</ReactMarkdown>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TermsPage;